baseurl = "/"
title = "The Donald Schulz Project"
theme = "hugo-theme-nix2"
languageCode = "en-us"
disqusShortname = "thedonaldschulzproject"

[menu]
  [[menu.header]]
    name = "news"
    weight = 0
    url = "post"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"
  [[menu.header]]
    name = "songs"
    weight = 2
    url = "songs"
  [[menu.header]]
    name = "albums"
    weight = 3
    url = "albums"  
  [[menu.header]]
    name = "playlists"
    weight = 0
    url = "playlists"

[params]
  GithubID = ""
  TwitterID = "donaldlschulz"
  LinkedInID = "donald-schulz-6b72833"
  MediumID = ""
  SpotifyID = "3w5iapzy08107ukj6p4gi6vgi"
  SoundcloudID = "thunderfoot-430950952"
  YoutubeID = "channel/UCMNgXQ9FN2OyK2KxplH-I2Q"
  TelegramID = ""
  InstagramID = "SchulzDL2"
  FacebookID = "100090232907939"
  Name = "Donald Schulz"
  HeaderUsername = ""
  HeaderHostname = "The Donald Schulz Project"
  Email = "thedonaldschulzproject@gmail.com"
  About = 'Welcome to the official website for all things pertaining to "The Donald Schulz Project".  Please sign up for our newsletter which is just an email that will be sent when ever we have news to share or annouce new songs that we just released.  Get the latest before anyone else does.  Thank you for stopping by.  Background information on the songs can be found under the songs menu.'
  ProfilePicture = "images/logo.png"
  Favicon = "images/favicon.png"
  BlogOnIndex = false

